name: data-bitcode-edsl
version: 0.1.0.0
synopsis: bitcode experimentation
license: BSD3
author: Moritz Angermann <moritz@lichtzwerge.de>
maintainer: Moritz Angermann <moritz@lichtzwerge.de>
copyright: lichtzwerge GmbH
category: Experimentation

github: angerman/bitcode-playground

dependencies:
  - base >= 4.7 && < 5
  - pretty >= 1.1
  - binary >= 0.8
  - bytestring >= 0.10
  - base16-bytestring
  - data-bitcode
  - data-bitcode-llvm
  - transformers

library:
  source-dirs:
    - src

