name: bitcode-playground
version: 0.1.0.0
synopsis: bitcode experimentation
license: BSD3
author: Moritz Angermann <moritz@lichtzwerge.de>
maintainer: Moritz Angermann <moritz@lichtzwerge.de>
copyright: lichtzwerge GmbH
category: Experimentation

github: lichtzwerge/bitcode-playground

dependencies:
  - base >= 4.7 && < 5
  - pretty >= 1.1
  - bytestring >= 0.10
  - base16-bytestring

library:
  source-dirs:
    - src
    - data-bitcode/src
    - data-bitcode-llvm/src

